_target_: src.tuners.rhythm_tuner.RhythmTuner
hparams:
  backbone:
    - resnet18
    - resnet50
    - regnetx_064
    - regnety_064
    - resnest50d
    - resnext50d_32x4d
  backbone_pretrained:
    - True
    - False
  rnn_type:
    - gru
    - lstm
  rnn_num_layers:
    low: 1
    high: 5
    log: False
  direction:
    - bi
    - uni
  lr:
    low: 0.00005
    high: 0.0005
    log: False
  t_max:
    low: 25
    high: 100
    log: False
  eta_min:
    low: 0.00005
    high: 0.00001
    log: False

module_params:
  interval: step
  connected_dir: ${connected_dir}
  devices: ${devices}
  accelerator: ${accelerator}
  strategy: ${strategy}
  log_every_n_steps: ${log_every_n_steps}
  precision: ${precision}
  accumulate_grad_batches: ${accumulate_grad_batches}
  max_epochs: ${epoch}
  monitor: ${monitor}
  mode: ${tracking_direction}
  patience: ${patience}
  min_delta: ${min_delta}

num_trials: ${num_trials}
seed: ${seed}
hparams_save_path: ${hparams_save_path}