_target_: src.tuners.rhythm_tuner.RhythmTuner
hparams:
  backbone:
    - resnet18
    - resnet50
    - regnetx_064
    - regnety_064
    - resnest50d
    - resnext50d_32x4d
  backbone_pretrained:
    - True
    - False
  rnn_type:
    - gru
    - lstm
  rnn_num_layers:
    low: 1
    high: 5
    log: False
  direction:
    - bi
    - uni
  lr:
    low: 5e-4
    high: 5e-3
    log: False
  weight_decay:
    low: 1e-2
    high: 1e-1
    log: False
  warmup_ratio:
    low: 1e-2
    high: 1e-1
    log: False
  eta_min_ratio:
    low: 5e-3
    high: 5e-2
    log: False

module_params:
  interval: step
  connected_dir: ${connected_dir}
  devices: ${devices}
  accelerator: ${accelerator}
  strategy: ${strategy}
  log_every_n_steps: ${log_every_n_steps}
  precision: ${precision}
  accumulate_grad_batches: ${accumulate_grad_batches}
  gradient_clip_val: ${gradient_clip_val}
  gradient_clip_algorithm: ${gradient_clip_algorithm}
  max_epochs: ${epoch}
  monitor: ${monitor}
  mode: ${tracking_direction}
  patience: ${patience}
  min_delta: ${min_delta}

direction: minimize
seed: ${seed}
num_trials: ${num_trials}
hparams_save_path: ${hparams_save_path}