_target_: src.architectures.rhythm_architecture.RythmArchitecture

model:
  _target_: src.architectures.models.customized_rhythmnet.CustomizedRhythmNet
  backbone: ${backbone}
  backbone_pretrained: ${backbone_pretrained}
  rnn_type: ${rnn_type}
  rnn_num_layers: ${rnn_num_layers}
  direction: ${direction}

lr: ${lr}
t_max: ${t_max}
eta_min: ${eta_min}
interval: step
project_dir: ${project_dir}
