_target_: src.architectures.rhythm_architecture.RythmArchitecture

model:
  _target_: src.architectures.models.customized_rhythmnet.CustomizedRhythmNet
  backbone: ${backbone}
  backbone_pretrained: ${backbone_pretrained}
  rnn_type: ${rnn_type}
  rnn_num_layers: ${rnn_num_layers}
  direction: ${direction}

strategy: ${strategy}
lr: ${lr}
weight_decay: ${weight_decay}
period: ${period}
eta_min: ${eta_min}
interval: step
connected_dir: ${connected_dir}
