_target_: src.datasets.tube_token_dataset.VIPLDataset
data_path: ${connected_dir}/data
metadata_path: ${connected_dir}/metadata
split: ${split.train}
split_ratio: ${split_ratio}
seed: ${seed}
file_path_column_name: ${file_path_column_name}
frame_index_column_name: ${frame_index_column_name}
tube_index_column_name: ${tube_index_column_name}
frame_rate_column_name: ${frame_rate_column_name}
bpm_column_name: ${bpm_column_name}
ecg_column_name: ${ecg_column_name}
num_devices: ${devices}
batch_size: ${batch_size}
clip_frame_size: ${clip_frame_size}
image_size: ${image_size}
augmentation_probability: ${augmentation_probability}
augmentations:
  - hflip
  - vflip