model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: val_rmse_loss
  mode: min
  save_top_k: 3
  save_last: True
  verbose: True
  dirpath: ${save_load_dir}/checkpoints/
  filename: ${model_name}-bs${batch_size}-epoch{epoch}
  auto_insert_metric_name: False

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: val_rmse_loss
  mode: min
  patience: 3
  min_delta: 0

model_summary:
  _target_: pytorch_lightning.callbacks.RichModelSummary
  max_depth: -1

rich_progress_bar:
