# @package _global_
defaults:
  - dataset_module: stmap_custom_dataset
  - architecture_module: basic_rhythm_archimodule
  - logger: wandb
  - hydra: hydra
  - callbacks: callbacks
  - trainer: trainer

project_dir: C:/project_Han/rppg-project
save_load_dir: D:/project_Han/rppg-project

seed: 2022

split:
  train: train
  val: val
  test: test

batch_size: 128

backbone: resnet50
backbone_pretrained: False
rnn_type: gru
rnn_num_layers: 1
direction: bi

lr: 0.0001

project_name: CustomizedRhythmNet
model_name: ${project_name}-${backbone}-${rnn_type}${rnn_num_layers}-${direction}

run_name: ${model_name}-train
work_dir: ${hydra:runtime.cwd}

tags: ${model_name}

epoch: 100
