# @package _global_
defaults:
  - dataset: tube_token_vipl_dataset
  - architecture: physformer_architecture
  - tuner: physformer_tuner
  - logger: wandb
  - hydra: hydra
  - callbacks: callbacks
  - trainer: trainer

package_name: rppg-project
project_dir: ${oc.env:PROJECT_DIR}/${package_name}
connected_dir: ${oc.env:CONNECTED_DIR}/${package_name}

seed: 2024

split:
  train: train
  val: val
  test: test
  predict: predict

batch_size: 32
workers_ratio: 8
use_all_workers: False

split_ratio: 1e-1
aug_interval: 30
file_path_column_name: file_path
frame_index_column_name: frame_index
tube_index_column_name: tube_index
frame_rate_column_name: frame_rate
bpm_column_name: BPM
ecg_column_name: ECG
clip_frame_size: 160
image_size: 128
augmentation_probability: 0.2

is_pretrained: False
patch_size: 4
feature_size: 4
sharp_gradient: 2.0
num_heads: 4
model_dims: 96
tcdc_kernel_size: 3
tcdc_stride: 1
tcdc_padding: 1
tcdc_dilation: 1
tcdc_groups: 1
tcdc_bias: False
tcdc_theta: 0.7
tcdc_eps: 1e-8
attention_dropout: 0.1
feed_forward_dims: 144
feed_forward_dropout: 0.1
num_layers: 12

min_bpm: 42
max_bpm: 180
std: 1.0
first_alpha: 0.1
first_beta: 1.0
alpha_factor: 1.0
beta_factor: 5.0

lr: 1e-5
weight_decay: 1e-2
warmup_ratio: 5e-2
eta_min_ratio: 1e-2

monitor: val_visual_loss
tracking_direction: min
patience: 15
min_delta: 0

devices: ${oc.decode:${oc.env:DEVICES}}
accelerator: gpu
strategy: ddp
log_every_n_steps: 10
precision: 32
accumulate_grad_batches: 1
gradient_clip_val: 1
gradient_clip_algorithm: norm
epoch: 30

model_name: PhysFormer
dataset_name: VIPL
mode: train

is_tuned: untuned
num_trials: 3
hparams_save_path: ${connected_dir}/hparams/${model_name}/${dataset_name}/${num_trials}_trials
tuned_hparams_path: ${hparams_save_path}/best_params.json

project_name: ${model_name}-${dataset_name}-${mode}
total_batch_size: bs=${batch_size}x${devices}x${accumulate_grad_batches}
length_info: data_max_length=${data_max_length}-target_max_length=${target_max_length}
save_detail: model_dims=${model_dims}-num_heads=${num_heads}-num_layers=${num_layers}-precision=${precision}-${total_batch_size}
resumed_step: 0
ckpt_path: ${callbacks.model_checkpoint.dirpath}/step=${step}.ckpt

submission_file_name: test
per_device_save_path: ${connected_dir}/sharded_results/${save_detail}-step=${step}
logit_name: ${save_detail}-step=${step}
pred_name: ${save_detail}-step=${step}
submission_name: ${save_detail}-step=${step}

user_name: ${oc.env:USER_NAME}
upload_tag: VIPL-HR-V1
model_detail: PhysFormer
num_safetensors: 10

run_name: ${project_name}
work_dir: ${hydra:runtime.cwd}