# @package _global_
defaults:
  - dataset: stmap_custom_dataset
  - tuner: rhythm_tuner
  - hydra: hydra

project_dir: /home/ddang/rppg-project

seed: 2024

split:
  train: train
  val: val
  test: test

batch_size: 128

num_trials: 3
save_path: ${project_dir}/hparams

dataset_name: Custom
project_name: CustomizedRhythmNet
model_name: ${dataset_name}-${project_name}

run_name: ${model_name}-tune
work_dir: ${hydra:runtime.cwd}

tags: ${model_name}

epoch: 10