# @package _global_
defaults:
  - dataset: stmap_custom_dataset
  - architecture: rhythm_architecture
  - logger: wandb
  - hydra: hydra
  - callbacks: callbacks
  - trainer: trainer

project_dir: /home/ddang/rppg-project
save_load_dir: /data

seed: 2024

split:
  train: train
  val: val
  test: test

batch_size: 128

backbone: resnet50
backbone_pretrained: False
rnn_type: gru
rnn_num_layers: 1
direction: bi

lr: 0.0001
t_max: 50
eta_min: 0.000025

is_tuned: True
num_trials: 3
tuned_hparams_path: ${project_dir}/hparams/${dataset_name}-${project_name}/${num_trials}_trials/best_params.json

dataset_name: Custom
project_name: CustomizedRhythmNet
model_name: ${dataset_name}-${project_name}-${backbone}-${rnn_type}${rnn_num_layers}-${direction}

ckpt_folder: ${callbacks.model_checkpoint.dirpath}
ckpt_path: ${ckpt_folder}${model_name}-bs${batch_size}-epoch${epoch}.ckpt

run_name: ${model_name}-test
work_dir: ${hydra:runtime.cwd}

tags: ${model_name}

epoch: 100
