# @package _global_
defaults:
  - dataset: stmap_custom_dataset
  - architecture: rhythm_architecture
  - tuner: rhythm_tuner
  - logger: wandb
  - hydra: hydra
  - callbacks: callbacks
  - trainer: trainer

package_name: rppg-project
project_dir: /home/ddang/${package_name}
connected_dir: /data/${package_name}

seed: 2024

split:
  train: train
  val: val
  test: test
  predict: predict

batch_size: 128

target_column_name: BPM

backbone: resnet50
backbone_pretrained: False
rnn_type: gru
rnn_num_layers: 1
direction: bi

lr: 0.0001
t_max: 50
eta_min: 0.000025

monitor: val_rmse_loss
tracking_direction: min
patience: 3
min_delta: 0

devices: 4
accelerator: gpu
strategy: ddp
log_every_n_steps: 10
precision: 32
accumulate_grad_batches: 1
epoch: 100

model_name: CustomizedRhythmNet
dataset_name: Custom
mode: train

is_tuned: tuned
num_trials: 3
hparams_save_path: ${connected_dir}/hparams/${model_name}/${dataset_name}/${num_trials}_trials
tuned_hparams_path: ${hparams_save_path}/best_params.json

project_name: ${model_name}-${dataset_name}-${mode}
total_batch_size: bs${batch_size}x${devices}x${accumulate_grad_batches}
save_detail: backbone${backbone}-rnn_type${rnn_type}-rnn_num_layers${rnn_num_layers}-direction${direction}-precision${precision}-${total_batch_size}
resumed_step: 0
ckpt_path: ${callbacks.model_checkpoint.dirpath}/epoch${epoch}.ckpt

submission_file_name: test
logit_name: ${save_detail}-epoch${epoch}
submission_name: ${save_detail}-epoch${epoch}

run_name: ${project_name}-${mode}
work_dir: ${hydra:runtime.cwd}