# @package _global_
defaults:
  - dataset_module: dataset
  - architecture_module: architecture_module
  - logger: wandb
  - hydra: hydra
  - callbacks: callbacks
  - trainer: trainer

seed: 2022

split:
  train: train
  val: val
  test: test

batch_size: 128

resnet_size: 50
rnn_type: gru
rnn_num_layers: 10
direction: bi

ckpt_folder: D:/project_Han/customized-rhythmnet/checkpoints/
ckpt_path: ${ckpt_folder}${model_name}-bs${batch_size}-epoch${epoch}.ckpt

model_name: CustomizedRhythmNet-${resnet_size}-${rnn_type}${rnn_num_layers}-${direction}

run_name: ${model_name}-test
work_dir: ${hydra:runtime.cwd}

tags: ${model_name}

epoch: 100
