# @package _global_
defaults:
  - dataset_module: dataset
  - architecture_module: architecture_module
  - logger: wandb
  - hydra: hydra
  - callbacks: callbacks
  - trainer: trainer

seed: 2022

split:
  train: train
  val: val
  test: test

batch_size: 128

cnn_model: resnet50
cnn_pretrained: False
rnn_type: gru
rnn_num_layers: 10
direction: bi

lr: 0.0001

model_name: CustomizedRhythmNet-${cnn_model}-${rnn_type}${rnn_num_layers}-${direction}

run_name: ${model_name}-train
work_dir: ${hydra:runtime.cwd}

tags: ${model_name}

epoch: 100
