_target_: src.architecture_modules.basic_archimodule.RbpmPlModule

model:
  _target_: src.architecture_modules.models.customized_rhythmnet.CustomizedRhythmNet
  backbone: ${backbone}
  backbone_pretrained: ${backbone_pretrained}
  rnn_type: ${rnn_type}
  rnn_num_layers: ${rnn_num_layers}
  direction: ${direction}

lr: ${lr}
t_max: 50
eta_min: 0.000025
interval: step
project_dir: ${project_dir}
